# Project: PRject_01
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/lib" -L"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -lwinmm "../../../../Dev C++/Dev_CPP/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32/libwinmm.a"
INCS     = -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/include" -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/include" -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"F:/INs pro/Dev_C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = PRject_01.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = F:\INs pro\Dev_C++\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
